spring.application.name=qomo-api-core

# IMPORTANTE: Desactivar gestión automática de Docker Compose de Spring Boot
spring.docker.compose.enabled=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.mail.host=localhost
spring.mail.port=1025