spring.application.name=platformcore-api-core
# IMPORTANTE: Desactivar gesti�n autom�tica de Docker Compose de Spring Boot
spring.docker.compose.enabled=false
# --- BASE DE DATOS ---
spring.datasource.url=${CORE_DB_URL}
spring.datasource.username=${CORE_DB_USER}
spring.datasource.password=${CORE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true