# ===== STAGE 1: BUILD =====
FROM node:22-alpine AS builder
WORKDIR /workspace

COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx run qomo-admin:build:production

# ===== STAGE 2: RUNTIME (NGINX) =====
FROM nginx:alpine
COPY --from=builder /workspace/dist/apps/qomo-admin/browser /usr/share/nginx/html
EXPOSE 80
