# ===== STAGE 1: BUILD =====
FROM node:22-alpine AS builder
WORKDIR /workspace

COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx run platformcore-admin:build:production

# ===== STAGE 2: RUNTIME (NGINX) =====
FROM nginx:alpine
COPY --from=builder /workspace/dist/apps/platformcore-admin/browser /usr/share/nginx/html
COPY nginx.admin.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
