server {
  listen 80;
  server_name _;

  # Health
  location = /health {
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  # ------------------------
  # APIs
  # ------------------------

  location = /v1/auth {
    proxy_pass http://api-users:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /v1/auth/ {
    proxy_pass http://api-users:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location = /v1/users {
    proxy_pass http://api-users:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /v1/users/ {
    proxy_pass http://api-users:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location = /v1/core {
    proxy_pass http://api-core:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /v1/core/ {
    proxy_pass http://api-core:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # ------------------------
  # Frontend Admin (estático)
  # ------------------------
  location /admin/ {
    proxy_pass http://frontend-admin:80/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # ------------------------
  # Frontend Client (SSR node)
  # ------------------------
  location / {
    proxy_pass http://frontend-client:4200;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;

    # SSR / websockets
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
