platformcore.security.cookie.secure=false
platformcore.security.cookie.same-site=Lax
platformcore.security.verification.cookie.secure=false
platformcore.security.verification.cookie.same-site=Lax
platformcore.security.csrf.cookie.secure=false
platformcore.security.csrf.cookie.same-site=Lax
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# ---- DEBUG
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG